import constants from '@geekcorp/constants';

export default {
	...constants,
	UPDATE_PALETTE: 'UPDATE_PALETTE',
	UNKNOWN: 'UNKNOWN',
	UPDATE_FIELD: 'UPDATE_FIELD',
	UPDATE_BUSY_STATE: 'UPDATE_BUSY_STATE',
	UPDATE_GLOBAL_ERROR: 'UPDATE_GLOBAL_ERROR',
	INITIATE_FORM_FIELDS: 'INITIATE_FORM_FIELDS',
	UPDATE_LOCALE: 'UPDATE_LOCALE'
}